// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAii7OWkij0nM8mFFP0NMLgHnARAphLqjQ',
    appId: '1:638694817445:web:7c1e9f3d8d75e19f59574c',
    messagingSenderId: '638694817445',
    projectId: 'vitmaya',
    authDomain: 'vitmaya.firebaseapp.com',
    storageBucket: 'vitmaya.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1SAjivFOJJuDh6pD1KqtbI1VtsD7xA8M',
    appId: '1:638694817445:android:3061046570bce2d459574c',
    messagingSenderId: '638694817445',
    projectId: 'vitmaya',
    storageBucket: 'vitmaya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnD79jgZetX-W9IMo2qMhfpmLlcCNjpg4',
    appId: '1:638694817445:ios:aeead19b2c6cba5f59574c',
    messagingSenderId: '638694817445',
    projectId: 'vitmaya',
    storageBucket: 'vitmaya.appspot.com',
    iosClientId: '638694817445-mcapueb0b5b1fvrsl2k8qvha9htslppm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vittamaya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnD79jgZetX-W9IMo2qMhfpmLlcCNjpg4',
    appId: '1:638694817445:ios:aeead19b2c6cba5f59574c',
    messagingSenderId: '638694817445',
    projectId: 'vitmaya',
    storageBucket: 'vitmaya.appspot.com',
    iosClientId: '638694817445-mcapueb0b5b1fvrsl2k8qvha9htslppm.apps.googleusercontent.com',
    iosBundleId: 'com.example.vittamaya',
  );
}
